name: assignment4
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Debug Build Context
      run: ls -R
    - name: Build and export stocks
      uses: docker/build-push-action@v5
      with:
        context: ./stocks
        file: ./stocks/Dockerfile
        tags: stocks:latest
        outputs: type=docker, dest=/tmp/stocks-image.tar
    - name: Build and export capital-gains
      uses: docker/build-push-action@v5
      with:
        context: ./capital-gains
        file: ./capital-gains/Dockerfile
        tags: capital-gains:latest
        outputs: type=docker, dest=/tmp/capital-gains-image.tar
    - name: Upload artifact stocks
      uses: actions/upload-artifact@v4
      with:
        name: stocks-image
        path: /tmp/stocks-image.tar
    - name: Upload artifact capital-gains
      uses: actions/upload-artifact@v4
      with:
        name: capital-gains-image
        path: /tmp/capital-gains-image.tar
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download stocks image
        uses: actions/download-artifact@v4
        with:
          name: stocks-image
          path: /tmp/
      - name: Download capital-gains image
        uses: actions/download-artifact@v4
        with:
          name: capital-gains-image
          path: /tmp/
      - name: Verify downloaded artifacts
        run: ls -l /tmp/
      - name: Load stocks image
        run: docker load --input /tmp/stocks-image.tar
      - name: Load capital-gains image
        run: docker load --input /tmp/capital-gains-image.tar
      - name: Check images are loaded
        run: docker image ls
      - name: Run Docker Compose
        run: docker compose up -d
      - name: Check containers are running
        run: docker ps
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          pip install pytest-dependency
      - name: Check for tests directory
        run: ls -l
      - name: Run tests with pytest
        run: |
          cd tests
          pytest -v assn4_tests.py > assn4_test_results.txt
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: assn4_test_results
          path: tests/assn4_test_results.txt
  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download stocks image
        uses: actions/download-artifact@v4
        with:
          name: stocks-image
          path: /tmp/
      - name: Download capital-gains image
        uses: actions/download-artifact@v4
        with:
          name: capital-gains-image
          path: /tmp/
      - name: Load stocks image
        run: docker load --input /tmp/stocks-image.tar
      - name: Load capital-gains image
        run: docker load --input /tmp/capital-gains-image.tar
      - name: Run Docker Compose
        run: docker compose up -d
      - name: Check containers are running
        run: docker ps
      - name: Post test stocks data
        run: |
          for i in {1..6}
          do
            curl -X POST http://localhost:5001/stocks -H "Content-Type: application/json" -d @tests/stock-objects/stock$i.json
          done
      - name: Verify inserted stocks
        run: curl -s "http://localhost:5001/stocks?shares=7"
      - name: Read and execute queries
        run: |
          touch response.txt  # Ensure the file exists

          echo "=== STARTING QUERY EXECUTION ===" | tee -a response.txt

          while IFS= read -r line; do
            echo "Processing query: $line" | tee -a response.txt  # Log the query execution

            service=$(echo "$line" | cut -d':' -f1 | xargs)
            query=$(echo "$line" | cut -d':' -f2- | xargs)

            if [ "$service" == "stocks" ]; then
              url="http://localhost:5001/stocks?$query"
            elif [ "$service" == "capital-gains" ]; then
              url="http://localhost:5003/capital-gains?$query"
            else
              echo "❌ Invalid service name in query: $line" | tee -a response.txt
              continue
            fi

            echo "🔍 Querying: $url" | tee -a response.txt  # Log the actual URL being requested

            response=$(curl -s -w "\nHTTP_CODE:%{http_code}" "$url")
            http_code=$(echo "$response" | grep -o 'HTTP_CODE:[0-9]*' | cut -d':' -f2)
            json_response=$(echo "$response" | sed '/HTTP_CODE/d')

            echo "🌐 HTTP Response Code: $http_code" | tee -a response.txt
            echo "📜 Raw Response: $json_response" | tee -a response.txt

            # If HTTP response code is not 200, log the error
            if [ "$http_code" != "200" ]; then
              echo "❌ ERROR: Received HTTP $http_code for $url" | tee -a response.txt
              continue
            fi

            # If response is empty, log it explicitly
            if [ -z "$json_response" ]; then
              echo "⚠️ WARNING: No response received for $url" | tee -a response.txt
            fi

            # Append formatted output to response.txt
            echo "query: $line" | tee -a response.txt
            echo "response: $json_response" | tee -a response.txt
            echo "" | tee -a response.txt  # Empty line for readability

          done < query.txt

          echo "=== QUERY EXECUTION COMPLETED ===" | tee -a response.txt
      - name: Upload response.txt
        uses: actions/upload-artifact@v4
        with:
          name: response
          path: response.txt